name: Dart Build and Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository
      - uses: actions/checkout@v4

      # Step 2: Install Flutter SDK
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable' # Use a specific Flutter version if required

      # Set up Dart environment
      - uses: dart-lang/setup-dart@9a04e6d73cca37bd455e0608d7e5092f881fd603

      # Install dependencies
      - name: Install dependencies
        run: flutter pub get

      # Build Flutter project (web, Android, iOS)
      - name: Build Flutter Web
        run: flutter build web --release
